### PR TITLE
Manthan- Files Uploaded as ZIP, Setup and other things in comment on this PR

### PR DESCRIPTION
**Pull request by thesmallstar**

### CODE REVIEW

**Comment by thesmallstar** [comment]
@strikertanmay  @jigar3 
I have added the files as a zip as I was facing some issue for a long time.  Sorry for that, hence I will be commenting on the Setup Procedure and other things, to avoid further pull Requests.

**Comment by thesmallstar** [comment]
Steps to Setup Project: 
Step 1: 
 To set up the Project you would need laravel installed on your computer,  First, install composer and then laravel. Instructions here:  https://laravel.com/docs/5.8/installation.
extract the following zip in the folder where PHP runs. 

Step 2: 
In phpmyadmin - Make a database name it "iota" and  download-import the following in that database: https://truetricks.com/ambu.sql

Step3:
Open the folder in which the project is kept and run command ' php artisan serve '.

A project is live on: localhost:8000

**Comment by thesmallstar** [comment]
In case the project is not correctly done on your laptop, I am giving detailed info of what I have done in the 
Tasks Completed.
Front page: 
(top right corner contains 3 links- Login for user,moderator, Register for both) 
1. Front Page: 



2.  Resgister Page: 
Register page has:
a. Front end Validations 
b. Backend Validations 
both the Validations work perfectly. 


3. Login Page for moderators: 
Note that: "I am a moderator",  is constant at disabled/cannot be changed. That is just to inform user that this is logging as moderator. 

Note: 
a. Front end validations
b. Back-end Validations 
c. Remember-me Button
d. Forgot password(works if email client is added)
works Perfectly. 

4. Login Page For user: 

a. Front end validations
b. Back-end Validations 
c. Remember-me Button
d. Forgot password(works if email client is added)
works Perfectly. 

The Login for moderator and user will take them to different home pages with Different options. 

Adding more comments with rest of the functions

**Comment by thesmallstar** [comment]
Logged in as Moderator:
1. Moderator can add new ambulances.
2. Check the status on the ambulance he have added. 




Note: The moderator can only see the ambulances added by him and not by others. 

Add new Ambulance: 
Moderator can click add new ambulance button and get the form. 


When he adds the form the table in the front gets updated with the Ambulance he added, and he get the success messege. 

The status of the ambulance can be viewed, That is, If the user has booked the ambulance the status is '1' else the status is '0'

**Comment by thesmallstar** [comment]
Logged in as a user: 
1. On login user see the Ambulances Added by **ALL**  the moderators.


2. User can click on any ambulance name Will open this form: 


3. Clicking the Book Ambulance button: 
 on Clicking the Book ambulance Button 2 things happen in the database:

1. Status of the ambulance is set to 1. 
2. User who has booked the ambulance gets added in the database. 





Flaws: Routes sometimes break when we book  the ambulance( this can be fixed in browser itself) 

The site is functioning and some information be printed directly from the database to the user like about the booked ambulance, etc that is not done. Also unbook the ambulance option should be there.

**Comment by thesmallstar** [comment]
Things I forgot to mention:
1. Login pages are responsive.
2. A demo user is added with email and password set to: user@gmail.com
3. A demo moderator is added with email and password set to: moderator@gmail.com

**Comment by strikertanmay** [comment]
U score 110 pts for webkriti related task and 55 pts for backbone related task

**Pull request merged**
